## Dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp

load_col:
    inter: [user_id, item_id, rating, timestamp]

NEG_PREFIX: neg_
LABEL_FIELD: label
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id

min_user_inter_num: 5
min_item_inter_num: 5

# Training settings
epochs: 50
train_batch_size: 256
learner: adam
learning_rate: 0.001
training_neg_sample_num: 0
eval_step: 1
stopping_step: 10

# Evaluation settings
eval_setting: TO_LS,full
metrics: ["Recall", "MRR","NDCG","Precision"]
valid_metric: MRR@10
eval_batch_size: 256
weight_decay: 0
topk: [5, 10, 20, 50]

# Directory setting
log_root: "./log/"
data_path: "./dataset/"

# DuoRec parameters
lmd: 0.1
lmd_sem: 0.1
tau: 1
contrast: 'us_x'
sim: 'dot'

# Model Architecture
hidden_size: 64
n_layers: 2
n_heads: 2
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: gelu
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: CE

# RAMRec Model  
enable_memory_management: True
memory_in_training: False
memory_size: 75
retrieval_k: 10  
memory_update_freq: 10
memory_gate_max_influence: 0.3 
memory_similarity_threshold: 0.4  
memory_temperature: 0.5 
enable_adaptive_k: True
adaptive_min_k: 3
adaptive_max_k: 20